#!/bin/sh
# PROVIDE: emby_webui
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="emby_webui"
rcvar="emby_webui_enable"

command="/usr/local/bin/npx"
command_args="serve -l 3000 /usr/local/share/chezzypufft"
command_interpreter="/usr/local/bin/node"

pidfile="/var/run/${name}.pid"
logfile="/var/log/${name}.log"

start_cmd="emby_webui_start"
stop_cmd="emby_webui_stop"
status_cmd="emby_webui_status"

emby_webui_start() {
    echo "Starting ${name}..."
    cd __PREFIX__/share/chezzypufft
    /usr/local/bin/node ${command} serve -l 3000 &>> ${logfile} &
    echo $$ > ${pidfile}
}

emby_webui_stop() {
    if [ -f ${pidfile} ]; then
        echo "Stopping ${name}..."
        kill $(cat ${pidfile}) 2>/dev/null
        rm -f ${pidfile}
    else
        echo "${name} not running"
    fi
}

emby_webui_status() {
    if [ -f ${pidfile} ]; then
        echo "${name} is running as pid $(cat ${pidfile})"
    else
        echo "${name} is not running"
    fi
}

load_rc_config ${name}
run_rc_command "$1"
